version: "3.8"
services:
  aws-sdk-go-v2_ssm_trial:
    container_name: AWS-SDK-Go-v2_ssm_trial
    build:
      context: .
      dockerfile: ./ssmTest/docker/dockerfile
    tty: true
    volumes:
      - ./ssmTest/src:/ssmTest
    ports:
      - 8080:8080
