version: "3.8"
services:
  terraform-trial:
    image: hashicorp/terraform:1.7.5
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-1}
    volumes:
      - ./trial/terraform:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true
