version: "3.8"
services:
  aws-sdk-go-v2-ssm:
    container_name: AWS-SDK-Go-v2-ssm
    build:
      context: .
      dockerfile: ./trial/docker/dockerfile
    tty: true
    volumes:
      - ./trial/src:/trial
    ports:
      - 8080:8080
